function(promxx_enable_sanitizers)
  set(oneValueArg TARGET)
  set(multiValueArg SANITIZERS)
  cmake_parse_arguments(ARG "" "${oneValueArg}" "${multiValueArg}" ${ARGN})

  if(NOT ARG_TARGET)
    message(FATAL_ERROR "Provide TARGET in 'promxx_enable_sanitizers'.")
  endif()
  if(NOT ARG_SANITIZERS)
    return()
  endif()

  if(MSVC)
    if("address" IN_LIST ARG_SANITIZERS)
      target_compile_options(${ARG_TARGET} INTERFACE /fsanitize=address)
    else()
      message(WARNING "MSVC only supports the 'address' sanitizer.")
    endif()
    return()
  endif()

  set(flags)

  if("address" IN_LIST ARG_SANITIZERS)
    list(APPEND flags -fsanitize=address)
  endif()
  if("leak" IN_LIST ARG_SANITIZERS)
    list(APPEND flags -fsanitize=leak)
  endif()
  if("undefined" IN_LIST ARG_SANITIZERS)
    list(APPEND flags -fsanitize=undefined)
  endif()
  if("thread" IN_LIST ARG_SANITIZERS)
    if("address" IN_LIST ARG_SANITIZERS OR "leak" IN_LIST ARG_SANITIZERS)
      message(FATAL_ERROR "ThreadSanitizer is not compatible with Address/LeakSanitizer.")
    endif()
    list(APPEND flags -fsanitize=thread)
  endif()
  if("memory" IN_LIST ARG_SANITIZERS)
    if(NOT CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
      message(FATAL_ERROR "MemorySanitizer is only supported by Clang.")
    endif()
    if("address" IN_LIST ARG_SANITIZERS OR "thread" IN_LIST ARG_SANITIZERS)
      message(FATAL_ERROR "MemorySanitizer is not compatible with Address/ThreadSanitizer.")
    endif()
    list(APPEND flags -fsanitize=memory -fno-optimize-sibling-calls -fsanitize-memory-track-origins=2)
  endif()

  if(flags)
    target_compile_options(${ARG_TARGET} INTERFACE ${flags})
    target_link_options(${ARG_TARGET} INTERFACE ${flags})
  endif()
endfunction()
